"""Generate docs/owasp_mapping.md from the real scenario library.

Run with:  python docs/generate_owasp_mapping.py

Reuses run_eval.run_all_scenarios() (the live pipeline, not a possibly-stale copy of
results/eval_report.json) so this table can never drift from what the scenarios and
detector actually produce - the same problem that made the original locked schema
example wrong before it was regenerated from a real run.
"""

from __future__ import annotations

import os
import sys
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, ROOT)

from run_eval import run_all_scenarios  # noqa: E402

OUTPUT_PATH = os.path.join(HERE, "owasp_mapping.md")


def _cell(text: str) -> str:
    """Escape a value for safe use inside a markdown table cell."""
    return text.replace("|", "\\|")


def build_markdown(results) -> str:
    by_tag = defaultdict(list)
    untagged = []
    for result in results:
        if result["owasp_tags"]:
            for tag in result["owasp_tags"]:
                by_tag[tag].append(result)
        else:
            untagged.append(result)

    lines = [
        "# Agent Sentinel — OWASP LLM Top 10 Mapping",
        "",
        "Generated by `docs/generate_owasp_mapping.py` from the real scenario library and "
        "the live detector output — do not hand-edit; regenerate instead so this can never "
        "drift from what the scenarios and detector actually do.",
        "",
        f"{len(results)} scenarios total, {len(by_tag)} distinct OWASP tags in use.",
        "",
    ]

    for tag in sorted(by_tag):
        entries = by_tag[tag]
        lines.append(f"## {tag}")
        lines.append("")
        lines.append(f"{len(entries)} scenario(s).")
        lines.append("")
        lines.append("| scenario_id | task | verdict | outcome | risk_score |")
        lines.append("|---|---|---|---|---|")
        for r in sorted(entries, key=lambda x: x["scenario_id"]):
            lines.append(
                f"| `{r['scenario_id']}` | {_cell(r['task'])} | {r['verdict']} | "
                f"{r['outcome']} | {r['risk_score']} |"
            )
        lines.append("")

    if untagged:
        lines.append("## Untagged (benign, no OWASP category)")
        lines.append("")
        lines.append("| scenario_id | task | verdict | outcome |")
        lines.append("|---|---|---|---|")
        for r in sorted(untagged, key=lambda x: x["scenario_id"]):
            lines.append(f"| `{r['scenario_id']}` | {_cell(r['task'])} | {r['verdict']} | {r['outcome']} |")
        lines.append("")

    return "\n".join(lines) + "\n"


def main() -> None:
    results = run_all_scenarios()
    markdown = build_markdown(results)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as fh:
        fh.write(markdown)
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
